server {
  # Listen SSL port
  listen 443 ssl http2 default_server;
  listen [::]:443 ssl http2 default_server;

  # Redirect traffic to secure port
  if ( $scheme != https ) {
    return 301 https://$host$request_uri;
  }

  # Certificates used for SSL
  ssl_certificate /etc/nginx/ssl/aci.crt;
  ssl_certificate_key /etc/nginx/ssl/aci.key;

  # Set client body size to 64M
  client_max_body_size 64M;
}